Initial skeleton structure
PlatformOfTrust/translator-skeleton-python pull request #1
Opened 2018-11-19 12:07 UTC by soderluk

Add initial structure for the Translator skeleton
Update readme
Add controller actions
Support for validating signatures and signing data

2018-11-19 15:10 UTC, edanchenkov approved these changes

2018-11-20 10:19 UTC, lietu requested changes
A few small changes please

2018-11-20 10:19 UTC, lietu commented on app/controllers.py
> +        'parameters': fields.Dict(allow_none=True),
Is it possible to define more specific validation here - like add some dummy field in the `parameters` object like "name" and validate it's a string?

2018-11-20 10:19 UTC, lietu commented on app/controllers.py
> +            raise ValidationFailed('Validation failed.')
How about just `raise`?

2018-11-20 11:57 UTC, soderluk commented on app/controllers.py
> +            raise ValidationFailed('Validation failed.')
The ValidationFailed() is the correct one to raise here.

2018-11-20 12:39 UTC, soderluk commented on app/controllers.py
> +        'parameters': fields.Dict(allow_none=True),
Added name as mandatory extra parameter

2018-11-20 12:40 UTC, lietu approved these changes

2018-11-20 12:42 UTC, merged